### ISSUE TITLE
How to load all IF's and channels without averaging?

### ISSUE THREAD

**Issue by KajWiik** [achael/eht-imaging#126]
Is it possible to load uvfits data without averaging over frequency (IF, channels) with `obsdata.load_uvfits()`?
My (deleted) example had a different problem: I assumed the data had more than one channels.

Anyway, it seems that obsdata.load_uvfits() cannot load multiple IF's and channels?

**Comment by achael** [comment]
Thanks for the issue and for using the software and I'm very very sorry for the late follow-up. Right now when I need to look at individual channels or IFs (rare for EHT data, which is why this functionality is crude) I load them into separate Obsdata objects with the IF and channel keyword arguments in the load_uvfits function.  I'm currently developing a better framework for unaveraged IF and channel data in the Obsdata object which I hope to make available in the next few months.
