### ISSUE TITLE
`afmhot` is Not A Perceptually Uniform Colormap

### ISSUE THREAD

**Issue by Miserlou** [achael/eht-imaging#85]
Cool picture, guys! But it seems like you've chosen a [non-perceptually uniform colormap](https://www.youtube.com/watch?v=xAoljeRJ3lU), which means that humans are likely to slightly misinterpret the image. It'd be great to see this historic image in something more human-comprehensible, like `viridis` or [plasma](https://matplotlib.org/tutorials/colors/colormaps.html) rather than `afmhot`!

**Comment by achael** [comment]
Hi Miserlou! You are absolutely right that afmhot is not perceptually uniform, however the images plotted in our papers (https://iopscience.iop.org/journal/2041-8205/page/Focus_on_EHT) do  *not* use amfhot. Instead, they use "amfhot_10us", a new colormap that is perceptually uniform and symmetric-in-chroma while approximating the appearance of afmhot. It was designed for the eht and implemented in the ehtplot library by Chi-kwan Chan and Lia Medeiros (https://github.com/liamedeiros/ehtplot).

Unfortunately, vanilla afmhot does remain the current default in the eht-imaging library for historical reasons, but this could change soon. Rest assured we thought of this issue and the paper images are indeed perceptually uniform!

**Comment by Miserlou** [comment]
Ah, wonderful, thanks for your reply!

**Comment by jbednar** [comment]
Ah, that explains a lot! The only perceptually uniform hot colormap that I've seen previously is the `fire` colormap included with our [colorcet](http://colorcet.pyiz.org) package, and your results looked perceptually uniform but not precisely those same colors.  On investigating, it was very confusing to see `afmhot` throughout the eht-imaging source code, and to see very nonuniform plots when re-running your examples, but from this issue it's clear. I would highly recommend that you change the default in eht-imaging to avoid encouraging the spread of `afmhot`.

For anyone who needs to know why not to use `afmhot`, you can see that it completely muddles the top end of the color values, making most of those colors indistinguishable:

![image](https://user-images.githubusercontent.com/1695496/56153500-f3f44980-5f7b-11e9-9a57-fc50dfc2fdcf.png)

The `fire` and presumably `afmhot_10us` maps allow all the numerical values to be distinguished across the full range, making the "comb" modulations here equally visible for all values:

![image](https://user-images.githubusercontent.com/1695496/56153524-fd7db180-5f7b-11e9-8dd7-22c25a3b372b.png)

These differences are very dramatic in the actual data as well, with `afmhot` looking overexposed because all the bright values blur together:

![image](https://user-images.githubusercontent.com/1695496/56152892-8267cb80-5f7a-11e9-89df-67070327ace3.png)

compared to `fire` showing all the detail for every numerical value range:

![image](https://user-images.githubusercontent.com/1695496/56152733-1f763480-5f7a-11e9-9082-326fb5cf6e5a.png)

Glad to see you caught that before publication, and please help encourage others to use perceptually uniform colormaps as well!

**Comment by endolith** [comment]
> Instead, they use "amfhot_10us", a new colormap that is perceptually uniform and symmetric-in-chroma while approximating the appearance of afmhot.

Typo for `afmhot_10us`
